CREATE TABLE IF NOT EXISTS INSTITUTIONS
(
    ID BIGINT AUTO_INCREMENT,
    NAME VARCHAR(255),
    ADDRESS VARCHAR(255),
    TYPE VARCHAR(255),
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS DOCTORS
(
    ID   BIGINT AUTO_INCREMENT,
    NAME VARCHAR(255),
    AGE INTEGER,
    SPECIALIZATION VARCHAR(255),
    INSTITUTION_ID BIGINT,
    PRIMARY KEY (ID),
    FOREIGN KEY (INSTITUTION_ID) REFERENCES INSTITUTIONS (ID)
);

CREATE TABLE IF NOT EXISTS PHARMACIES
(
    ID   BIGINT AUTO_INCREMENT,
    NAME VARCHAR(255),
    ADDRESS VARCHAR(255),
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS MEDICAMENTS
(
    ID   BIGINT AUTO_INCREMENT,
    NAME VARCHAR(255),
    TYPE VARCHAR(50),
    UNIT VARCHAR(20),
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS EXISTENCES
(
    ID   BIGINT AUTO_INCREMENT,
    COUNT INTEGER,
    PRICE DOUBLE,
    VOLUME INTEGER,
    MEDICAMENT_ID BIGINT,
    PHARMACY_ID BIGINT,
    PRIMARY KEY (ID),
    FOREIGN KEY (MEDICAMENT_ID) REFERENCES MEDICAMENTS (ID),
    FOREIGN KEY (PHARMACy_ID) REFERENCES PHARMACIES (ID)
);

CREATE TABLE IF NOT EXISTS PATIENTS
(
    ID   BIGINT AUTO_INCREMENT,
    NAME VARCHAR(255),
    AGE INTEGER,
    ADDRESS VARCHAR(255),
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS ORDERS
(
    ID BIGINT AUTO_INCREMENT,
    VOLUME INTEGER,
    DESCRIPTION VARCHAR(255),
    MEDICAMENT_ID BIGINT,
    PRIMARY KEY (ID),
    FOREIGN KEY (MEDICAMENT_ID) REFERENCES MEDICAMENTS (ID)
);

CREATE TABLE IF NOT EXISTS PRESCRIPTIONS
(
    ID BIGINT AUTO_INCREMENT,
    PERIOD INTEGER,
    SERIAL VARCHAR(12),
    USE BOOLEAN,
    DATE DATE,
    DOCTOR_ID BIGINT,
    PATIENT_ID BIGINT,
    ORDER_ID BIGINT,
    PRIMARY KEY (ID),
    FOREIGN KEY (DOCTOR_ID) REFERENCES DOCTORS (ID),
    FOREIGN KEY (PATIENT_ID) REFERENCES PATIENTS (ID),
    FOREIGN KEY (ORDER_ID) REFERENCES ORDERS (ID)
);

CREATE TABLE IF NOT EXISTS USERS
(
    ID   BIGINT AUTO_INCREMENT,
    NAME VARCHAR(255),
    PASSWORD VARCHAR(255),
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS ROLES
(
    ID   BIGINT AUTO_INCREMENT,
    NAME VARCHAR(255),
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS  USER_ROLE (
    USER_ID BIGINT,
    ROLE_ID BIGINT,
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
    FOREIGN KEY (ROLE_ID) REFERENCES ROLES(ID)
);